changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - fix
    - title: Performance Improvements
      labels:
        - performance
    - title: Refactoring
      labels:
        - refactor
    - title: Testing
      labels:
        - test
    - title: Continuous Integration
      labels:
        - ci
    - title: Documentation
      labels:
        - documentation
    - title: Build System and Dependencies
      labels:
        - build
    - title: Style
      labels:
        - style
    - title: Other Changes
      labels:
        - "*"
