# This file configures the Hasura CLI, a local development (and deployment) tool.
# It is required to run the Hasura CLI (even if empty).

version: 3
endpoint: http://localhost:8080/
metadata_directory: metadata
migrations_directory: migrations
admin_secret: aerie
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
