name: "\U0001F41E Bug Report"
description: Report an issue with Aerie.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: checked-for-duplicates
    attributes:
      label: Checked for duplicates
      description: Have you checked for duplicate issue tickets?
      options:
        - "No - I haven't checked"
        - "Yes - I've already checked"
    validations:
      required: true
  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - "No - This is a new bug"
        - "Yes - This worked in a previous version"
    validations:
      required: true
  - type: input
    id: bug-version
    attributes:
      label: Version
      description: What version of Aerie are you observing this bug in?
      placeholder: "1.4.0, 1.5.0, develop, etc."
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please describe how to reproduce the problem you ran into. If the description is vague (e.g. just a generic error message) and has no reproduction, it will receive a "needs reproduction" label. If no reproduction is provided within a reasonable time-frame, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include browser console and server logs around the time this bug occurred. Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please provide information on the environment you discovered this bug in.
      render: shell
      placeholder: Browsers, System, Binaries
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of this issue.
      options:
        - Minor
        - Moderate
        - Major
        - Critical
    validations:
      required: true
