apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aerie-dev
  name: aerie-merlin-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerie-merlin-worker
  template:
    metadata:
      labels:
        app: aerie-merlin-worker
    spec:
      containers:
        - name: aerie-merlin-worker
          image: ghcr.io/nasa-ammos/aerie-merlin-worker:develop
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/merlin_file_store
              name: aerie-file-store
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: |
                -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=WARN -Dorg.slf4j.simpleLogger.logFile=System.err
            - name: MERLIN_WORKER_DB
              value: aerie_merlin
            - name: MERLIN_WORKER_DB_PORT
              value: "5432"
            - name: MERLIN_WORKER_DB_SERVER
              value: postgres
            - name: MERLIN_WORKER_LOCAL_STORE
              value: /usr/src/app/merlin_file_store
            - name: UNTRUE_PLAN_START
              value: "2000-01-01T11:58:55.816Z"
            - name: MERLIN_WORKER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: AERIE_USERNAME
            - name: MERLIN_WORKER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: AERIE_PASSWORD
      restartPolicy: Always
      volumes:
        - name: aerie-file-store
          persistentVolumeClaim:
            claimName: aerie-file-store
            readOnly: true
