name: Publish

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - uses: actions/cache@v3
        with:
          path: |
            ./build
            ./**/build
          key: ${{ runner.os }}-gradle-${{ github.sha }}
      - uses: gradle/wrapper-validation-action@v1
      - name: assemble project
        run: ./gradlew assemble --parallel --no-daemon

  build:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - uses: actions/cache@v3
        with:
          path: |
            ./build
            ./**/build
          key: ${{ runner.os }}-gradle-${{ github.sha }}
      - name: check for output
        run: ls ./merlin-server/build
